ALTER TABLE "User" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "autoRecord" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "recordingPath" TEXT;
ALTER TABLE "User" ADD COLUMN "recordQuality" TEXT NOT NULL DEFAULT 'source';
ALTER TABLE "User" ADD COLUMN "recordFps" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "User" ADD COLUMN "recordEncoder" TEXT NOT NULL DEFAULT 'nvenc';
