import type { FundamentalCategory } from './fundamentals'

export const FUNDAMENTALS_FR: FundamentalCategory[] = [
  {
    id: 'general_champion_pool',
    label: 'Général — Pool de champions',
    fundamentals: [
      {
        id: 'mastery',
        label: 'Maîtrise',
        description: 'Votre maîtrise mécanique sur vos champions : combos, séquencement des sorts, annulations d\'animations et mécaniques avancées.',
        kpis: [
          { id: 'combo_execution', label: 'Exécution des combos', description: 'Capacité à exécuter régulièrement des combos complets et annulations d\'animations' },
          { id: 'ability_sequencing', label: 'Séquencement des sorts', description: 'Utiliser les sorts dans l\'ordre optimal selon la situation' },
          { id: 'edge_case_mechanics', label: 'Mécaniques avancées', description: 'Gérer les interactions mécaniques rares (combos Flash, astuces de terrain)' },
          { id: 'mechanical_consistency', label: 'Régularité mécanique', description: 'Reproduire de façon fiable vos mécaniques de base pendant toute la partie, pas seulement dans les situations idéales' },
          { id: 'input_cleanliness', label: 'Propreté des inputs', description: 'Éviter les missclicks, erreurs de buffer et inputs paniqués sous pression' },
        ],
      },
      {
        id: 'champion_identity',
        label: 'Identité du champion',
        description: 'Comprendre le rôle de votre champion dans chaque draft, les archétypes de match-up, et les conditions de victoire selon la composition.',
        kpis: [
          { id: 'draft_role_understanding', label: 'Rôle dans la draft', description: 'Savoir ce que votre champion doit faire dans la composition actuelle' },
          { id: 'matchup_archetypes', label: 'Archétypes de match-up', description: 'Reconnaître la dynamique de lane (poke vs sustain, all-in vs échange court)' },
          { id: 'wincon_per_comp', label: 'Condition de victoire', description: 'Adapter son style de jeu à la condition de victoire optimale de l\'équipe' },
          { id: 'lane_plan_clarity', label: 'Clarté du plan de lane', description: 'Avoir un plan de lane clair en early selon le match-up, les paths de jungle et l\'objectif de vague' },
          { id: 'skirmish_role_understanding', label: 'Rôle en escarmouche', description: 'Comprendre si votre champion doit engager, peel, flank ou follow dans les petits fights' },
        ],
      },
      {
        id: 'pool_coherence',
        label: 'Cohérence du pool',
        description: 'La capacité de votre pool à couvrir la méta, s\'adapter aux bans et éviter les lacunes selon les situations.',
        kpis: [
          { id: 'meta_adaptability', label: 'Adaptabilité à la méta', description: 'Capacité à ajuster votre pool selon l\'évolution de la méta' },
          { id: 'situational_picks', label: 'Picks situationnels', description: 'Avoir des alternatives quand vos champions principaux sont bannis ou contrés' },
          { id: 'role_coverage', label: 'Couverture de rôle', description: 'Pas de lacune critique dans votre pool (AP vs AD, tank vs carry)' },
          { id: 'blind_pick_safety', label: 'Sécurité en blind pick', description: 'Avoir au moins un blind pick fiable qui reste jouable dans la plupart des match-ups' },
          { id: 'depth_over_width', label: 'Profondeur plutôt que largeur', description: 'Garder assez de répétition sur vos picks principaux au lieu de trop vous disperser' },
        ],
      },
    ],
  },
  {
    id: 'general_overall',
    label: 'Général — Vue d\'ensemble',
    fundamentals: [
      {
        id: 'summoner_spells',
        label: 'Sorts d\'invocateur',
        description: 'Maîtrise des sorts d\'invocateur — timing du Flash, usage d\'Ignite/Soins/TP/Fantôme pour un impact maximal.',
        kpis: [
          { id: 'flash_timing', label: 'Timing du Flash', description: 'Utiliser le Flash au bon moment (plays offensifs, fuites clutch)' },
          { id: 'combat_spell_usage', label: 'Sorts de combat', description: 'Timing optimal d\'Ignite/Soins/Barrière dans les échanges et all-ins' },
          { id: 'tp_macro', label: 'Macro du TP', description: 'TP au bon endroit au bon moment pour les objectifs/flancs' },
          { id: 'defensive_spell_discipline', label: 'Discipline des sorts défensifs', description: 'Ne pas gaspiller ses sorts défensifs trop tôt, trop tard, ou pour des situations à faible valeur' },
          { id: 'enemy_summoner_punish', label: 'Punition des sorts ennemis', description: 'Reconnaître et exploiter immédiatement les fenêtres où les sorts ennemis ne sont plus disponibles' },
        ],
      },
      {
        id: 'cooldown_tracking',
        label: 'Suivi des temps de recharge',
        description: 'Suivre les sorts d\'invocateur ennemis, les temps de recharge des sorts clés et vos propres fenêtres de recharge.',
        kpis: [
          { id: 'enemy_summs_tracking', label: 'Suivi des sorts ennemis', description: 'Mémoriser les timers de Flash/TP/Ignite ennemis' },
          { id: 'key_ability_cds', label: 'CD des sorts clés', description: 'Suivre les ultimes ennemis, sorts de CC et sorts d\'évasion' },
          { id: 'own_cd_awareness', label: 'Conscience de ses CD', description: 'Ne pas sur-engager quand ses sorts clés sont en recharge' },
          { id: 'window_punishment', label: 'Punition des fenêtres', description: 'Passer à l\'action quand une fenêtre favorable apparaît réellement après avoir track un cooldown' },
        ],
      },
      {
        id: 'itemization',
        label: 'Optimisation des objets',
        description: 'Construire les bons objets au bon moment selon le match-up, l\'état du jeu et les besoins de l\'équipe.',
        kpis: [
          { id: 'first_item_priority', label: 'Premier objet', description: 'Choisir le bon premier objet selon le match-up de lane' },
          { id: 'situational_builds', label: 'Builds situationnels', description: 'Adapter le build à l\'état de la partie (armure vs résistance magique, dégâts vs survie)' },
          { id: 'component_timing', label: 'Timing des composants', description: 'Acheter les bons composants à chaque rappel (ne pas laisser l\'or dormir)' },
          { id: 'defensive_item_timing', label: 'Timing des objets défensifs', description: 'Respecter le profil de dégâts ennemi en achetant vos outils défensifs avant d\'être puni' },
          { id: 'utility_item_value', label: 'Valeur des objets utilitaires', description: 'Reconnaître quand anti-heal, cleanse ou utilitaire d\'équipe apporte plus que des dégâts bruts' },
        ],
      },
      {
        id: 'map_awareness',
        label: 'Conscience de la carte',
        description: 'Fréquence de vérification de la minimap, anticipation des menaces, et réaction aux pings de disparition et plays globaux.',
        kpis: [
          { id: 'minimap_frequency', label: 'Fréquence minimap', description: 'Regarder régulièrement la minimap toutes les quelques secondes' },
          { id: 'threat_anticipation', label: 'Anticipation des menaces', description: 'Prédire les ganks ou roams avant qu\'ils surviennent' },
          { id: 'mia_reaction', label: 'Réaction aux MIA', description: 'Ajuster son positionnement quand des ennemis disparaissent' },
          { id: 'camera_control', label: 'Contrôle de la caméra', description: 'Utiliser les mouvements de caméra pour récolter plus d\'informations que la minimap seule' },
          { id: 'crossmap_reaction', label: 'Réaction crossmap', description: 'Réagir rapidement aux escarmouches, dives et plays globaux ailleurs sur la carte' },
        ],
      },
      {
        id: 'csing_pathing',
        label: 'CS / Déplacement',
        description: 'Efficacité du last hit, objectifs CS/min (7+ pour les laners), et déplacement optimal sous pression.',
        kpis: [
          { id: 'last_hit_accuracy', label: 'Précision du last hit', description: 'Last hit régulier y compris sous la tour' },
          { id: 'cs_per_min', label: 'CS/min', description: 'Maintenir un CS élevé tout au long de la partie (objectif 7+)' },
          { id: 'pathing_efficiency', label: 'Efficacité du déplacement', description: 'Se déplacer efficacement entre camps/lanes pour maximiser les revenus' },
          { id: 'wave_catch_rate', label: 'Récupération des vagues', description: 'Récupérer les side waves avant qu\'elles ne meurent inutilement sous les tours' },
          { id: 'downtime_optimization', label: 'Optimisation des temps morts', description: 'Utiliser les temps morts pour wards, camps, resets ou préparation de vague au lieu d\'errer sans but' },
        ],
      },
      {
        id: 'tempo',
        label: 'Tempo',
        description: 'Savoir quand accélérer (post-kill, post-objectif) vs ralentir pour reset et farmer.',
        kpis: [
          { id: 'accelerate_timing', label: 'Accélération', description: 'Exploiter les avantages après kills, objectifs ou premier sang' },
          { id: 'slow_down_judgment', label: 'Jugement de ralentissement', description: 'Reconnaître quand farmer et attendre plutôt que forcer des plays' },
          { id: 'reset_timing', label: 'Timing du reset', description: 'Se rappeler et reset aux moments optimaux sans perdre le tempo' },
          { id: 'sequence_chaining', label: 'Enchaînement des séquences', description: 'Enchaîner proprement vagues, recalls, camps et objectifs sans gaspiller le tempo' },
        ],
      },
      {
        id: 'wincon_identification',
        label: 'Identification de la condition de victoire',
        description: 'Lire la draft et l\'état du jeu pour identifier comment votre équipe gagne (teamfight, pick, split-push, montée en puissance).',
        kpis: [
          { id: 'draft_reading', label: 'Lecture de la draft', description: 'Identifier la condition de victoire de votre équipe depuis la sélection des champions' },
          { id: 'adapting_wincon', label: 'Adapter la condition de victoire', description: 'Ajuster le plan quand la condition de victoire originale échoue' },
          { id: 'snowball_vs_scale', label: 'Snowball vs montée en puissance', description: 'Savoir quand exploiter une avance vs jouer prudemment et monter en puissance' },
          { id: 'resource_allocation', label: 'Allocation des ressources', description: 'Diriger vagues, camps, vision et pression vers le champion ou la lane qui sert le mieux la win condition' },
          { id: 'fallback_plan', label: 'Plan de secours', description: 'Avoir une deuxième voie de victoire quand le plan principal devient irréaliste' },
        ],
      },
    ],
  },
  {
    id: 'general_mental',
    label: 'Général — Mental',
    fundamentals: [
      {
        id: 'resilience',
        label: 'Résilience',
        description: 'Jouer en retard sans tilt, récupérer après une série de défaites, et maintenir sa concentration.',
        kpis: [
          { id: 'tilt_management', label: 'Gestion du tilt', description: 'Rester calme et concentré après des morts, mauvais plays ou erreurs de coéquipiers' },
          { id: 'playing_from_behind', label: 'Jouer en retard', description: 'Faire des plays intelligents et peu risqués quand votre équipe perd' },
          { id: 'loss_streak_recovery', label: 'Récupération après défaites', description: 'Faire des pauses et reset son mental après des défaites consécutives' },
          { id: 'mistake_reset_speed', label: 'Vitesse de reset après erreur', description: 'Revenir mentalement dans la partie dans la minute qui suit au lieu de perdre le reste de la game' },
        ],
      },
      {
        id: 'fortitude',
        label: 'Ténacité',
        description: 'Mentalité de ne jamais abandonner, extraire des leçons même des parties perdues, et rester mentalement dans la partie.',
        kpis: [
          { id: 'never_give_up', label: 'Ne jamais abandonner', description: 'Jouer pour gagner même dans les parties difficiles (les ennemis font aussi des erreurs)' },
          { id: 'lesson_extraction', label: 'Extraction de leçons', description: 'Trouver au moins un enseignement de chaque partie, victoire ou défaite' },
          { id: 'mental_endurance', label: 'Endurance mentale', description: 'Maintenir la qualité de jeu tout au long des longues sessions' },
          { id: 'discipline_under_frustration', label: 'Discipline sous frustration', description: 'Garder son plan de jeu au lieu de forcer des plays à faible pourcentage par frustration' },
        ],
      },
      {
        id: 'shotcalling_communication',
        label: 'Appels de jeu / Communication',
        description: 'Leadership positif par pings, éviter les pings intempestifs, et partager proactivement des informations utiles.',
        kpis: [
          { id: 'positive_pings', label: 'Pings positifs', description: 'Utiliser les pings pour communiquer objectifs, dangers et plays de façon constructive' },
          { id: 'no_spam', label: 'Éviter le spam', description: 'Ne pas perturber les coéquipiers avec des pings excessifs ou un chat négatif' },
          { id: 'info_sharing', label: 'Partage d\'infos', description: 'Pinger les timers de sorts d\'invocateur, positions ennemies et timers d\'objectifs' },
          { id: 'ping_clarity', label: 'Clarté des pings', description: 'Rendre vos pings faciles à comprendre en évitant les signaux contradictoires ou brouillons' },
          { id: 'timer_callouts', label: 'Annonces de timers', description: 'Communiquer à l\'avance les timers d\'objectifs, vagues et cooldowns avant qu\'ils deviennent urgents' },
        ],
      },
    ],
  },
  {
    id: 'micro',
    label: 'Micro',
    fundamentals: [
      {
        id: 'spacing',
        label: 'Espacement',
        description: 'Gestion de la distance pendant les échanges, esquive des skillshots et patterns de kiting.',
        kpis: [
          { id: 'trade_distance', label: 'Distance d\'échange', description: 'Rester à la limite de votre portée pendant les échanges pour minimiser les contre-attaques' },
          { id: 'skillshot_dodging', label: 'Esquive de skillshots', description: 'Esquiver régulièrement les skillshots ennemis importants' },
          { id: 'kiting_patterns', label: 'Patterns de kiting', description: 'Se déplacer en attaquant efficacement tout en maintenant la distance optimale' },
          { id: 'tethering', label: 'Tethering', description: 'Jouer juste à l\'entrée et à la sortie de la portée ennemie pour bait les sorts et contrôler les échanges' },
        ],
      },
      {
        id: 'aggression_calibration',
        label: 'Calibrage de l\'agressivité',
        description: 'Lire quand échanger, pocher, all-in, ou désengager selon les PV, la mana et les recharges.',
        kpis: [
          { id: 'trade_windows', label: 'Fenêtres d\'échange', description: 'Reconnaître quand vous avez une fenêtre d\'échange favorable (CD ennemi utilisé, avantage de vague)' },
          { id: 'all_in_timing', label: 'Timing de l\'all-in', description: 'S\'engager en all-in seulement quand vous avez la pression du kill' },
          { id: 'disengage_judgment', label: 'Jugement de désengagement', description: 'Savoir quand se retirer d\'un échange perdant avant que ça s\'aggrave' },
          { id: 'resource_check_before_commit', label: 'Vérification des ressources', description: 'Vérifier PV, mana, sorts et taille de vague avant de forcer l\'agression' },
          { id: 'jungle_respect_in_aggression', label: 'Respect de la jungle dans l\'agression', description: 'Ajuster son niveau d\'agressivité selon la position probable du jungler au lieu de trader dans le vide' },
        ],
      },
      {
        id: 'positioning',
        label: 'Positionnement',
        description: 'Utiliser les murs et le terrain comme outils, rester à la portée optimale, et ne pas s\'aventurer trop loin.',
        kpis: [
          { id: 'terrain_usage', label: 'Utilisation du terrain', description: 'Utiliser les murs, buissons et points de passage à votre avantage' },
          { id: 'attack_range_management', label: 'Gestion de la portée', description: 'Rester à portée maximale tout en infligeant des dégâts régulièrement' },
          { id: 'overextend_awareness', label: 'Conscience du sur-engagement', description: 'Ne pas pousser trop loin sans vision ou soutien' },
          { id: 'threat_line_awareness', label: 'Conscience des lignes de menace', description: 'Comprendre depuis quels angles les ennemis peuvent réellement vous menacer avant de vous avancer' },
        ],
      },
      {
        id: 'limits_knowledge',
        label: 'Connaissance des limites',
        description: 'Connaître les pics de puissance de votre champion, les "déclencheurs silencieux" ennemis (niveau 6, pics d\'objets) et les seuils de punition.',
        kpis: [
          { id: 'power_spike_awareness', label: 'Conscience des pics de puissance', description: 'Savoir quand votre champion est fort et jouer en conséquence' },
          { id: 'enemy_spike_respect', label: 'Respect des pics ennemis', description: 'Respecter les pics de puissance ennemis (niveau 6, objet terminé)' },
          { id: 'punish_thresholds', label: 'Seuils de punition', description: 'Connaître les dégâts exacts pour décider quand s\'engager pour un kill' },
          { id: 'lethal_calculation', label: 'Calcul du lethal', description: 'Estimer si votre combo complet tue réellement avant de vous engager' },
          { id: 'limit_testing_quality', label: 'Qualité du limit testing', description: 'Tester ses limites de manière intentionnelle et apprendre, plutôt que coinflip sans contexte' },
        ],
      },
    ],
  },
  {
    id: 'early_game_laning',
    label: 'Début de partie — Lane',
    fundamentals: [
      {
        id: 'matchup_knowledge',
        label: 'Connaissance du match-up',
        description: 'Recherche pré-partie sur les counters et runes, plus adaptation en jeu aux picks inattendus.',
        kpis: [
          { id: 'pregame_research', label: 'Recherche pré-partie', description: 'Consulter les runes, builds et style de jeu spécifiques au match-up avant la partie' },
          { id: 'adaptation', label: 'Adaptation en jeu', description: 'S\'adapter aux picks inattendus ou styles de jeu non préparés' },
          { id: 'level_one_plan', label: 'Plan de niveau 1', description: 'Commencer la lane avec une idée claire de qui gagne le niveau 1, le niveau 2 et les trois premières vagues' },
          { id: 'rune_setup_accuracy', label: 'Précision des runes', description: 'Choisir les runes et shards qui correspondent réellement au match-up et au plan de lane' },
        ],
      },
      {
        id: 'wave_management',
        label: 'Gestion de la vague',
        description: 'Contrôler les vagues de sbires pour créer des avantages : freeze, push lent, push rapide, rebond et manipulation avancée.',
        kpis: [
          { id: 'wave_state_awareness', label: 'Conscience de l\'état de vague', description: 'Connaître l\'état actuel de la vague et ce qu\'elle deviendra' },
          { id: 'wave_manipulation_execution', label: 'Exécution de la manipulation', description: 'Réussir à mettre en place l\'état de vague désiré' },
          { id: 'wave_objective_sync', label: 'Sync vague-objectif', description: 'Aligner les états de vague avec les objectifs et rappels' },
          { id: 'enemy_wave_punish', label: 'Punition des erreurs de vague', description: 'Punir les erreurs adverses quand l\'ennemi thin, crash ou tient mal la vague' },
          { id: 'lane_safety_through_wave', label: 'Sécurité via la vague', description: 'Utiliser la vague pour réduire le risque de gank au lieu de traiter la gestion de vague comme une mécanique isolée' },
        ],
        subcategories: [
          {
            id: 'freeze',
            label: 'Freeze',
            description: 'Maintenir la vague juste dans la portée de votre tour pour deny les CS ennemis et faciliter les ganks.',
            kpis: [
              { id: 'freeze_setup', label: 'Mise en place du freeze', description: 'Réussir à mettre en place et maintenir une position de freeze' },
              { id: 'freeze_hold', label: 'Maintien du freeze', description: 'Maintenir le freeze sur plusieurs vagues sans le briser' },
              { id: 'freeze_deny', label: 'Deny par freeze', description: 'Utiliser le freeze pour deny un maximum de CS à l\'ennemi' },
              { id: 'freeze_break_response', label: 'Réponse au break du freeze', description: 'Réagir correctement quand l\'ennemi tente de casser le freeze avec sorts, recall ou aide jungle' },
            ],
          },
          {
            id: 'slow_push',
            label: 'Push lent',
            description: 'Construire une grande vague pour crasher et faire des dégâts de tour, préparer un dive, ou prendre un avantage au rappel.',
            kpis: [
              { id: 'slow_push_setup', label: 'Mise en place du push lent', description: 'Construire correctement un push lent en tuant uniquement les sbires mages' },
              { id: 'slow_push_crash', label: 'Crash du push lent', description: 'Timer le crash pour maximiser les dégâts de tour ou l\'opportunité de dive' },
              { id: 'slow_push_timing', label: 'Timing du push lent', description: 'Démarrer le push lent au bon moment pour votre plan' },
              { id: 'stacked_wave_protection', label: 'Protection de la grosse vague', description: 'Garder la vague stackée assez saine pour qu\'elle atteigne la tour sans prendre trop de dégâts' },
            ],
          },
          {
            id: 'fast_push',
            label: 'Push rapide',
            description: 'Nettoyer la vague instantanément pour créer du temps pour roam, rappel, ou contester des objectifs.',
            kpis: [
              { id: 'fast_push_speed', label: 'Vitesse du push rapide', description: 'Nettoyer la vague le plus vite possible sans rater de CS' },
              { id: 'fast_push_purpose', label: 'Objectif du push rapide', description: 'Avoir une raison claire de push rapidement (roam, rappel, objectif)' },
              { id: 'post_push_conversion', label: 'Conversion après shove', description: 'Utiliser réellement la fenêtre de tempo créée pour une action utile après le shove' },
            ],
          },
          {
            id: 'bounce',
            label: 'Rebond',
            description: 'Timer un crash de push lent pour que la vague rebondisse vers vous avec la priorité de lane.',
            kpis: [
              { id: 'bounce_timing', label: 'Timing du rebond', description: 'Timer correctement le crash pour que la vague revienne vers vous' },
              { id: 'bounce_exploitation', label: 'Exploitation du rebond', description: 'Utiliser le rebond pour mettre en place un freeze ou une position de farm sécurisée' },
              { id: 'bounce_patience', label: 'Patience sur le rebond', description: 'Laisser le rebond se développer naturellement au lieu de le casser en tapant trop la vague suivante' },
            ],
          },
          {
            id: 'wave_for_trade',
            label: 'Avancé — Vague pour échange',
            description: 'Positionner une vague qui crash pour forcer l\'ennemi sous sa tour avant d\'engager un échange favorable.',
            kpis: [
              { id: 'wave_trade_setup', label: 'Setup vague pour échange', description: 'Construire un avantage de vague avant d\'initier un échange' },
              { id: 'minion_damage_awareness', label: 'Dégâts des sbires', description: 'Utiliser les dégâts de votre plus grande vague dans les échanges prolongés' },
              { id: 'tower_pressure_trade_window', label: 'Fenêtre d\'échange sous pression tour', description: 'Reconnaître quand la pression de la tour force l\'ennemi à choisir entre last hit et réponse à votre trade' },
            ],
          },
          {
            id: 'wave_for_objective',
            label: 'Avancé — Vague pour objectif',
            description: 'Synchroniser les pushs lents avec les timers de Baron/Drake pour créer de la pression sur la carte.',
            kpis: [
              { id: 'objective_wave_sync', label: 'Sync vague-objectif', description: 'Démarrer des pushs lents 60-90s avant le spawn d\'un objectif' },
              { id: 'cross_map_pressure', label: 'Pression sur la carte', description: 'Créer de la pression en side-lane pendant que votre équipe conteste un objectif' },
              { id: 'recall_after_setup', label: 'Recall après setup', description: 'Utiliser la pression de vague créée pour prendre un bon reset avant le fight d\'objectif' },
            ],
          },
        ],
      },
      {
        id: 'trades',
        label: 'Échanges',
        description: 'Timer les échanges avec les recharges de sorts et l\'état de la vague, exécuter les patterns d\'échange, et reconnaître les échanges perdants tôt.',
        kpis: [
          { id: 'trade_timing', label: 'Timing des échanges', description: 'Engager quand les sorts clés ennemis sont en recharge' },
          { id: 'trade_pattern', label: 'Pattern d\'échange', description: 'Exécuter les bons combos d\'échange (échange court vs prolongé vs all-in)' },
          { id: 'losing_trade_recognition', label: 'Reconnaissance des échanges perdants', description: 'Se retirer tôt quand un échange commence mal' },
          { id: 'minion_advantage_usage', label: 'Utilisation de l\'avantage de sbires', description: 'Prendre en compte la taille de la vague pour trader plus fort avec soutien des sbires et plus soft contre elle' },
          { id: 'damage_accounting', label: 'Bilan des dégâts', description: 'Évaluer si l\'échange vous a vraiment favorisé en PV, cooldowns et état de lane' },
        ],
      },
      {
        id: 'recall_timing',
        label: 'Timing du rappel',
        description: 'Se rappeler sur les fenêtres optimales de PV/mana, synchroniser avec le crash de vague, et minimiser la perte de CS.',
        kpis: [
          { id: 'recall_window', label: 'Fenêtre de rappel', description: 'Choisir le bon moment pour se rappeler (après le crash, avec bons PV/mana)' },
          { id: 'cs_loss_minimization', label: 'Minimisation de la perte CS', description: 'Perdre un minimum de CS au rappel en le synchronisant avec l\'état de la vague' },
          { id: 'item_spike_recall', label: 'Rappel pour pic d\'objet', description: 'Se rappeler quand vous avez assez d\'or pour un composant clé' },
          { id: 'objective_sync_recall', label: 'Recall synchronisé objectif', description: 'Timer les recalls pour revenir avec le tempo avant dragon, héraut ou une grosse décision de side wave' },
        ],
      },
      {
        id: 'fog_usage',
        label: 'Utilisation du brouillard',
        description: 'Utiliser le brouillard de rivière/tri-buisson pour simuler des roams, attirer l\'agressivité ou préparer des flancs.',
        kpis: [
          { id: 'fog_pressure', label: 'Pression par brouillard', description: 'Entrer dans le brouillard pour créer de l\'incertitude et forcer l\'ennemi à jouer prudemment' },
          { id: 'fake_roam', label: 'Faux roam', description: 'Simuler un roam pour forcer l\'ennemi à suivre ou perdre des CS' },
          { id: 'bush_control', label: 'Contrôle des buissons', description: 'Utiliser les buissons de lane et de rivière à votre avantage dans les échanges et ganks' },
          { id: 'reentry_timing', label: 'Timing de réapparition', description: 'Réapparaître du brouillard au meilleur moment pour punir l\'avidité ou le mauvais positionnement adverse' },
        ],
      },
      {
        id: 'roam_gank_timing',
        label: 'Timing des roams / ganks',
        description: 'Identifier quand la priorité de lane ouvre une fenêtre de roam et choisir des chemins efficaces.',
        kpis: [
          { id: 'priority_recognition', label: 'Reconnaissance de la priorité', description: 'Savoir quand vous avez la priorité de lane pour roam en sécurité' },
          { id: 'roam_pathing', label: 'Chemin du roam', description: 'Prendre le chemin le plus rapide ou le plus surprenant vers la lane cible' },
          { id: 'roam_cost_assessment', label: 'Évaluation du coût du roam', description: 'Peser la perte de CS/tour contre le gain potentiel du roam' },
          { id: 'wave_prep_before_roam', label: 'Préparation de vague avant roam', description: 'Préparer correctement la lane avant de partir pour que le roam ne soit pas puni instantanément' },
          { id: 'roam_commit_quality', label: 'Qualité de commit du roam', description: 'Annuler rapidement les mauvais roams au lieu d\'insister sur un move à faible valeur' },
        ],
      },
      {
        id: 'gank_effectiveness',
        label: 'Efficacité des ganks',
        description: 'Mettre en place la vision avant les ganks, bloquer les chemins d\'évasion, et coordonner les kills.',
        kpis: [
          { id: 'gank_setup', label: 'Setup du gank', description: 'Mettre en place la vision et le positionnement avant de gank une lane' },
          { id: 'gank_execution', label: 'Exécution du gank', description: 'Bloquer correctement, timer le CC et sécuriser les kills' },
          { id: 'countergank_awareness', label: 'Conscience du contregank', description: 'Être conscient de la position du jungler ennemi avant de gank' },
          { id: 'flash_forcing_value', label: 'Valeur du flash forcé', description: 'Considérer un flash ou TP brûlé comme un vrai gain même sans kill' },
          { id: 'post_gank_conversion', label: 'Conversion post-gank', description: 'Transformer un gank réussi en plaques, vague deny, vision ou contrôle d\'objectif' },
        ],
      },
      {
        id: 'vision_setup',
        label: 'Mise en place de la vision',
        description: 'Warden dans des emplacements clés tôt — rivière, tri-buisson, wards roses sur les entrées.',
        kpis: [
          { id: 'early_warding', label: 'Warding précoce', description: 'Placer le premier ward au bon moment et au bon endroit' },
          { id: 'pink_ward_usage', label: 'Utilisation des wards roses', description: 'Acheter et placer des wards de contrôle dans des spots à haute valeur' },
          { id: 'ward_timing', label: 'Timing du warding', description: 'Warden de façon proactive (avant les ganks) plutôt que réactive' },
          { id: 'lane_specific_warding', label: 'Warding spécifique au match-up', description: 'Choisir des spots de ward adaptés au match-up, à l\'état de lane et au path jungle ennemi' },
          { id: 'vision_refresh_cycle', label: 'Cycle de rafraîchissement de vision', description: 'Renouveler la vision expirée ou nettoyée au lieu de laisser de longues fenêtres sans info' },
        ],
      },
      {
        id: 'jungle_tracking',
        label: 'Suivi de la jungle',
        description: 'Utiliser les timers de camps, la vision de rivière et les infos de carte pour prédire la position du jungler ennemi.',
        kpis: [
          { id: 'jungler_prediction', label: 'Prédiction du jungler', description: 'Prédire dans quel quadrant se trouve le jungler ennemi' },
          { id: 'camp_timer_knowledge', label: 'Connaissance des timers de camps', description: 'Connaître les timers de respawn des camps pour suivre le pathing du jungler' },
          { id: 'position_adjustment', label: 'Ajustement de position', description: 'Ajuster la position en lane selon la position prédite du jungler' },
          { id: 'opening_info_gathering', label: 'Collecte d\'infos en ouverture', description: 'Utiliser la vision niveau 1, les premiers états de lane et la première apparition du jungler pour identifier son ouverture probable' },
          { id: 'jungler_cs_verification', label: 'Vérification du CS jungler', description: 'Vérifier le CS du jungler ennemi quand il apparaît pour déduire son clear, son côté de départ et les camps restants' },
          { id: 'camp_deduction', label: 'Déduction des camps', description: 'Déduire les camps encore disponibles selon le timing, le nombre de CS, la logique du path et les reveals sur la carte' },
        ],
      },
      {
        id: 'resource_management',
        label: 'Gestion des ressources',
        description: 'Gérer les ratios d\'échanges en PV et mana, et savoir quand jouer passif pour récupérer.',
        kpis: [
          { id: 'hp_management', label: 'Gestion des PV', description: 'Éviter les dégâts inutiles et gérer les PV dans les échanges' },
          { id: 'mana_management', label: 'Gestion de la mana', description: 'Ne pas manquer de mana avant les moments clés (combats, ganks, rappels)' },
          { id: 'potion_timing', label: 'Timing des potions', description: 'Utiliser les potions aux moments optimaux (pendant les échanges, pas à PV plein)' },
          { id: 'resource_to_wave_conversion', label: 'Conversion ressources-vague', description: 'Dépenser PV et mana d\'une manière qui sécurise la priorité, le crash ou le contrôle de vague' },
        ],
      },
      {
        id: 'weak_strong_side',
        label: 'Côté faible / fort',
        description: 'Jouer prudemment en côté faible (juste farmer) et maximiser l\'agentivité et la pression en côté fort.',
        kpis: [
          { id: 'weak_side_safety', label: 'Sécurité en côté faible', description: 'Jouer prudemment et farmer quand votre jungler est du côté opposé' },
          { id: 'strong_side_aggression', label: 'Agressivité en côté fort', description: 'Être proactif et agressif quand vous avez le soutien du jungler' },
          { id: 'side_identification', label: 'Identification du côté', description: 'Identifier correctement de quel côté vous êtes et adapter votre jeu' },
          { id: 'dive_respect', label: 'Respect du dive', description: 'Respecter les grosses vagues et le setup adverse quand vous êtes isolé en weak side' },
          { id: 'crossmap_trade_understanding', label: 'Compréhension du trade crossmap', description: 'Comprendre ce que votre équipe doit gagner ailleurs quand vous devez céder de la pression en weak side' },
        ],
      },
      {
        id: 'level_up_timers',
        label: 'Montées de niveau',
        description: 'Exploiter les pics de niveaux 2/3/6/9/11/16 en gérant la priorité de lane pour les atteindre en premier.',
        kpis: [
          { id: 'level_2_spike', label: 'Pic niveau 2', description: 'Pousser pour atteindre le niveau 2 en premier et échanger dès qu\'il est atteint' },
          { id: 'level_6_spike', label: 'Pic niveau 6', description: 'Timer le pic de puissance du niveau 6 pour une opportunité de kill' },
          { id: 'xp_lead_maintenance', label: 'Maintien de l\'avance XP', description: 'Maintenir les avantages d\'XP via une bonne gestion des vagues' },
          { id: 'pre_spike_preparation', label: 'Préparation avant spike', description: 'Préparer correctement la vague et le spacing avant que le spike de niveau n\'arrive réellement' },
          { id: 'enemy_spike_denial', label: 'Déni du spike ennemi', description: 'Reculer ou ajuster la vague pour empêcher l\'ennemi de pleinement exploiter son propre spike' },
        ],
      },
    ],
  },
  {
    id: 'mid_late_macro',
    label: 'Milieu / Fin de partie — Macro',
    fundamentals: [
      {
        id: 'decision_making',
        label: 'Prise de décision',
        description: 'Choisir entre objectifs, lanes, primes — lire l\'horloge du jeu et savoir quand s\'engager vs reset.',
        kpis: [
          { id: 'objective_priority', label: 'Priorité des objectifs', description: 'Choisir le play le plus précieux quand plusieurs options existent' },
          { id: 'game_clock_reading', label: 'Lecture de l\'horloge', description: 'Comprendre quels plays sont appropriés selon le timer de partie' },
          { id: 'commit_vs_reset', label: 'S\'engager vs reset', description: 'Décider correctement quand combattre et quand reculer' },
          { id: 'risk_reward_assessment', label: 'Évaluation risque / récompense', description: 'Juger si le downside d\'un play est acceptable par rapport à son upside réaliste' },
          { id: 'numbers_advantage_play', label: 'Exploitation du surnombre', description: 'Reconnaître et jouer rapidement les fenêtres où votre équipe a temporairement plus de joueurs dans la zone' },
        ],
      },
      {
        id: 'lane_assignment',
        label: 'Attribution des lanes',
        description: 'Déploiement optimal des rôles avant de quitter la base — qui va où pour une pression maximale.',
        kpis: [
          { id: 'assignment_awareness', label: 'Conscience de l\'attribution', description: 'Aller dans la bonne lane après chaque rappel ou mort' },
          { id: 'matchup_consideration', label: 'Considération du match-up', description: 'Attribuer les lanes selon qui peut gérer le laneur adverse' },
          { id: 'pressure_distribution', label: 'Distribution de la pression', description: 'S\'assurer que toutes les lanes sont couvertes et la pression répartie' },
          { id: 'objective_side_assignment', label: 'Attribution côté objectif', description: 'Envoyer les bons champions du côté de la carte qui compte pour le prochain objectif' },
        ],
      },
      {
        id: 'wave_management_objectives',
        label: 'Gestion des vagues pour les objectifs',
        description: 'Construire des pushs lents sur 2-3 lanes avant Baron/Dragon pour créer de la pression et des fenêtres de rappel.',
        kpis: [
          { id: 'multi_lane_setup', label: 'Setup multi-lanes', description: 'Mettre en place des pushs lents dans plusieurs lanes avant les objectifs' },
          { id: 'objective_prep_timing', label: 'Timing de préparation', description: 'Démarrer le setup des vagues 60-90s avant le spawn des objectifs' },
          { id: 'pressure_creation', label: 'Création de pression', description: 'Forcer l\'ennemi à choisir entre les vagues et les objectifs' },
          { id: 'crash_timing_precision', label: 'Précision du crash', description: 'Faire arriver les side waves exactement au moment où votre équipe veut lancer le setup d\'objectif' },
          { id: 'reset_sync_after_setup', label: 'Sync du reset après setup', description: 'Utiliser le setup de vague pour acheter, heal et reprendre le tempo avant le fight d\'objectif' },
        ],
      },
      {
        id: 'vision_control',
        label: 'Contrôle de la vision',
        description: 'Warding stratégique autour des objectifs, utilisation des balayeurs pour nier la vision, et manipulation du brouillard de guerre.',
        kpis: [
          { id: 'objective_vision', label: 'Vision des objectifs', description: 'Warden la zone Baron/Dragon avant le spawn' },
          { id: 'vision_denial', label: 'Négation de la vision', description: 'Utiliser le balayeur pour détruire les wards ennemies dans les zones clés' },
          { id: 'fog_manipulation', label: 'Manipulation du brouillard', description: 'Effectuer des rotations dans les zones non wardées pour créer de l\'incertitude' },
          { id: 'vision_line_discipline', label: 'Discipline de la ligne de vision', description: 'Tenir une ligne de vision cohérente au lieu de poser des wards isolées sans protection' },
          { id: 'zone_ownership', label: 'Contrôle de zone', description: 'Utiliser l\'avantage de vision pour réellement contrôler les entrées et refuser l\'accès à l\'ennemi' },
        ],
        subcategories: [
          {
            id: 'ward_timing_macro',
            label: 'Timing du warding',
            description: 'Warden la fosse Dragon/Baron 60s avant le spawn pour suivre l\'approche ennemie.',
            kpis: [
              { id: 'pre_objective_ward', label: 'Ward pré-objectif', description: 'Placer de la vision 60+ secondes avant le spawn de l\'objectif' },
              { id: 'rotation_vision', label: 'Vision des rotations', description: 'Warden les chemins utilisés par les ennemis pour se rendre aux objectifs' },
              { id: 'ward_refresh', label: 'Rafraîchissement des wards', description: 'Renouveler les wards expirées ou détruites avant l\'ouverture de la fenêtre de fight' },
            ],
          },
          {
            id: 'control_ward_placement',
            label: 'Placement des wards de contrôle',
            description: 'Placer des wards roses dans des spots à haute valeur — entrée de fosse, buisson de rivière, tri ennemi.',
            kpis: [
              { id: 'pink_high_value', label: 'Rose haute valeur', description: 'Placer des wards de contrôle dans des emplacements offrant une valeur de vision maximale' },
              { id: 'pink_maintenance', label: 'Maintenance des roses', description: 'Toujours avoir une ward de contrôle sur la carte' },
              { id: 'pink_protection', label: 'Protection des roses', description: 'Défendre vos wards de contrôle quand c\'est safe au lieu de les donner gratuitement' },
            ],
          },
          {
            id: 'vision_denial_macro',
            label: 'Négation de la vision',
            description: 'Utilisation du balayeur pour nier la vision ennemie avant les plays clés.',
            kpis: [
              { id: 'sweeper_usage', label: 'Utilisation du balayeur', description: 'Utiliser le balayeur en approchant des objectifs ou en préparant des picks' },
              { id: 'clearing_priority', label: 'Priorité de nettoyage', description: 'Prioriser la destruction des wards ennemies les plus impactantes' },
              { id: 'denial_timing', label: 'Timing du déni', description: 'Nettoyer la vision assez proche du play pour que l\'ennemi ne puisse pas tout remettre' },
            ],
          },
          {
            id: 'fog_of_war_play',
            label: 'Jeu dans le brouillard',
            description: 'Effectuer des rotations cachées pour tromper l\'ennemi et créer des avantages.',
            kpis: [
              { id: 'hidden_rotation', label: 'Rotation cachée', description: 'Se déplacer dans des zones non wardées pour surprendre l\'ennemi' },
              { id: 'macro_fog_pressure', label: 'Pression par brouillard', description: 'Disparaître de la carte pour créer de la pression sans s\'engager' },
              { id: 'reveal_discipline', label: 'Discipline de reveal', description: 'Éviter de se montrer inutilement sur une wave ou une ward avant que le play caché soit prêt' },
            ],
          },
        ],
      },
      {
        id: 'rotation_positioning',
        label: 'Positionnement lors des rotations',
        description: 'Jouer avec le brouillard en side-lanes, gestion du tempo pendant les rotations, et éviter les sur-rotations.',
        kpis: [
          { id: 'side_lane_fog', label: 'Brouillard en side-lane', description: 'Utiliser le brouillard de guerre en side-lane pour menacer sans être vu' },
          { id: 'rotation_tempo', label: 'Tempo des rotations', description: 'Arriver aux combats et objectifs avec un bon timing' },
          { id: 'over_rotation_avoidance', label: 'Éviter la sur-rotation', description: 'Ne pas quitter sa lane trop tôt et perdre CS/tours inutilement' },
          { id: 'catch_prevention', label: 'Prévention des catches', description: 'Pathing pendant les rotations de manière à éviter le facecheck et les picks avant le play' },
          { id: 'teammate_sync', label: 'Synchronisation équipe', description: 'Rotate sur le même timing que vos coéquipiers au lieu d\'arriver seul ou trop tard' },
        ],
      },
    ],
  },
  {
    id: 'teamfighting',
    label: 'Combats d\'équipe',
    fundamentals: [
      {
        id: 'role_identification',
        label: 'Identification du rôle',
        description: 'Attribution des rôles pré-combat — frontliner, plongeur, protecteur, DPS, ou initiateur — selon la composition.',
        kpis: [
          { id: 'role_clarity', label: 'Clarté du rôle', description: 'Savoir exactement votre mission dans les combats avant qu\'ils commencent' },
          { id: 'role_execution', label: 'Exécution du rôle', description: 'Exécuter votre rôle assigné de façon régulière pendant les combats' },
          { id: 'role_adaptation', label: 'Adaptation du rôle', description: 'Adapter votre rôle quand la situation l\'exige (ex: protéger au lieu de plonger)' },
          { id: 'target_access_planning', label: 'Plan d\'accès à la cible', description: 'Prévoir à l\'avance comment vous allez réellement atteindre ou menacer les cibles importantes' },
        ],
      },
      {
        id: 'cd_management_fights',
        label: 'Gestion des temps de recharge',
        description: 'Attendre les recharges clés ennemies avant d\'engager, suivre les sorts pendant les combats.',
        kpis: [
          { id: 'patience', label: 'Patience', description: 'Ne pas tout utiliser immédiatement — attendre le bon moment' },
          { id: 'key_cd_tracking', label: 'Suivi des CD clés', description: 'Suivre Zhonya, GA, ultimes clés pendant les combats' },
          { id: 'spell_staggering', label: 'Décalage des sorts', description: 'Ne pas superposer les CC ou bursts avec ceux des coéquipiers' },
          { id: 'reengage_timing', label: 'Timing de réengage', description: 'Reconnaître le moment exact pour réentrer après la disparition des gros cooldowns ou invulnérabilités' },
          { id: 'cooldown_baiting', label: 'Appât des cooldowns', description: 'Utiliser son mouvement ou un léger commit pour faire tomber les sorts clés avant le vrai engage' },
        ],
      },
      {
        id: 'threat_assessment',
        label: 'Évaluation des menaces',
        description: 'Identifier la source de danger la plus élevée (carry fed, tank initiateur) et réagir en premier.',
        kpis: [
          { id: 'primary_threat_id', label: 'Identification menace principale', description: 'Identifier rapidement qui inflige le plus de dégâts ou a le plus d\'impact' },
          { id: 'focus_target', label: 'Cible prioritaire', description: 'Focus la bonne cible (pas toujours l\'ennemi le plus proche)' },
          { id: 'threat_re_evaluation', label: 'Réévaluation des menaces', description: 'Changer de cible quand les priorités changent en cours de combat' },
          { id: 'peel_priority', label: 'Priorité du peel', description: 'Reconnaître quand protéger son carry vaut plus que courir sur la backline ennemie' },
          { id: 'threat_range_awareness', label: 'Conscience des portées de menace', description: 'Respecter les portées d\'engage et de dégâts des menaces ennemies clés avant qu\'elles ne touchent' },
        ],
      },
      {
        id: 'prefight_positioning',
        label: 'Positionnement pré-combat',
        description: 'Arriver à la position optimale avant que les combats commencent — angles de flanc, couverture de vision, contrôle de portée.',
        kpis: [
          { id: 'arrival_positioning', label: 'Positionnement à l\'arrivée', description: 'Être au bon endroit avant que le combat commence (pas en train de rattraper)' },
          { id: 'flank_setup', label: 'Mise en place du flanc', description: 'Préparer des flancs quand votre champion en bénéficie' },
          { id: 'safe_angle', label: 'Angle sécurisé', description: 'Se positionner avec une voie d\'évasion en tête avant de s\'engager' },
          { id: 'choke_control', label: 'Contrôle des choke points', description: 'Utiliser terrain et points d\'entrée étroits pour limiter les options ennemies avant le fight' },
          { id: 'information_setup', label: 'Préparation de l\'information', description: 'Se positionner assez près pour agir tout en gardant l\'avantage d\'information via vision et brouillard' },
        ],
      },
    ],
  },
]
